config/routes.rb
Rails.application.routes.draw do
  resource :incoming_message, only: [:create]

  # REMINDER shallow nests index, new, create actions
  # This scope will cause complaints for `bundle exec` commands if you've not yet
  # loaded the schema for the relevant environment.
  scope "(:skin)", constraints: { format: 'html' } do
    namespace :admin do
      root "claims#index"
      
      post "/letters/:id/file", to: "letters#file", as: :file_letter
      resources :claim_companies, only: [:destroy]
      resources :claims, only: [:index, :show, :edit, :update, :create] do
        resources :letters, shallow: true
        resources :messages, only: [:index, :new, :create]
        resources :documents, only: [:new, :create]
        resources :notes, only: [:index]
        resources :claim_companies, only: [:new, :create]
      end
      resources :profiles, only: [:edit, :update] do
        resource :address, only: [:new, :create]
      end
      resources :addresses, only: [:edit, :update, :destroy]
      resources :documents, only: [:show, :edit, :update, :destroy]

      resources :companies, :awards, :claim_stages
      resources :supergroups, path: "organisations", format: /html|json/
      resources :groups, path: "campaigns"

      get "/preview", to: "previews#show"
    end

    root "claims#new"

    # TODO will devise tolerate singular user?
    # No need for multiple user visibility except in the admin space
    devise_for :users, controllers: { invitations: 'users/invitations' }
    resources  :users

    resource   :profile
    # TODO nest singular address - split forms?

    # TODO singular resource for basic namespace claim?
    resources  :claims do
      resources :documents, shallow: true
      resources :claim_companies, shallow: true
    end

    resources  :companies, only: [:show] do
      # TODO singular resource for company_address?
      resources :company_addresses, shallow: true
      resources :claim_companies, shallow: true
    end
    
    resource   :feedback, only: [:new, :create], controller: 'feedback'

    resource   :feedback, only: [:new, :create], controller: 'feedback'

    # JSON lookup routes
    resources  :companies, only: [:index], constraints: { format: 'json' }
    resources  :addresses, only: [:edit, :update], constraints: { format: 'json' }

    # Membership API
    get "/membership", to: "memberships#show", as: :memberships
    # Help and custom pages
    get "/pages/:page", to: "pages#show", as: :pages

  end
end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < Admin::BaseController
  before_action :set_address, except: [:new, :create]
  before_action :set_profile, only: [:new, :create]
  
  # GET /admin/profiles/1/address/new
  def new
    @address = Address.new
  end
  
  # POST /admin/profiles/1/address
  def create
    @address = @profile.build_address(address_params)
    
    respond_to do |format|
      if @profile.save
        format.html { redirect_to admin_claim_path(@profile.user.claim), notice: "Address added." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /addresses/1/edit
  def edit
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to admin_root_path, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to admin_root_path, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.  
  def set_address
    @address = Address.find(params[:id])
  end
  
  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def address_params
    params.require(:address).permit(:street_address, :town, :province, :postal_code, :country)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
  # def form_title
  #   (@address.addressable || @addressable).class.to_s.downcase + "_title"
  # end

  def markdown_postal_format(addressee, address)
    [
      addressee,
      address.street_address.gsub(/(\r?\n)/, '  \1'),
      address.town,
      address.province + "&emsp;" + address.postal_code
    ].reject(&:blank?).join("  \n")
  end
  
  def states_list
    locale_list_for_select_options('helpers.addresses.states_list')
  end
  
  def full_country_list
    locale_list_for_select_options('helpers.addresses.country_list')
  end
end

app/views/admin/addresses/_address.html.haml
%h4
  = title
  - unless edit.blank?
    %small= link_to("(#{edit})", edit_admin_address_path(address))

:markdown
  #{ markdown_model(address) }

app/views/admin/addresses/edit.html.haml
= form_for(@address, url: admin_address_path(@address), html: { class: "form", multipart: true }) do |f|
  = render partial: "layouts/errors", locals: { resource: @address }

  %fieldset
    %legend= "Edit address"
    = f.hidden_field :country, value: "AU"

    .form-group
      = f.label :street_address, class: "control-label"
      %br/
      = f.text_area :street_address, class: "form-control", rows: 2
    .form-group
      = f.label :town, class: "control-label"
      %br/
      = f.text_field :town, class: "form-control"
    .form-group
      = f.label :province, class: "control-label"
      %br/
      = f.select :province, options_for_select(states_list, @address.province), {}, { class: "form-control" }
    .form-group
      = f.label :postal_code, class: "control-label"
      %br/
      = f.text_field :postal_code, class: "form-control"
    .form-group
      = f.label :country, class: "control-label"
      %br/
      = f.select :country, options_for_select(country_list, "AU"), {}, { class: "form-control", placeholder: "Type your country..." }

  .actions.text-right= f.submit "Submit", class: "btn btn-default"

app/views/admin/addresses/new.html.haml
= form_for([@profile, @address], url: admin_profile_address_path([@profile, @address]), html: { class: "form", multipart: true }) do |f|
  = render partial: "layouts/errors", locals: { resource: @address }

  %fieldset
    %legend= "New address"
    = f.hidden_field :country, value: "AU"

    .form-group
      = f.label :street_address, class: "control-label"
      %br/
      = f.text_area :street_address, class: "form-control", rows: 2
    .form-group
      = f.label :town, class: "control-label"
      %br/
      = f.text_field :town, class: "form-control"
    .form-group
      = f.label :province, class: "control-label"
      %br/
      = f.text_field :province, class: "form-control"
    .form-group
      = f.label :postal_code, class: "control-label"
      %br/
      = f.text_field :postal_code, class: "form-control"
    .form-group
      = f.label :country, class: "control-label"
      %br/
      = f.select :country, options_for_select(country_list, "AU"), {}, { class: "form-control", placeholder: "Type your country..." }

  .actions.text-right= f.submit "Submit", class: "btn btn-default"