config/routes.rb
Rails.application.routes.draw do
  resource :incoming_message, only: [:create]

  # REMINDER shallow nests index, new, create actions
  # This scope will cause complaints for `bundle exec` commands if you've not yet
  # loaded the schema for the relevant environment.
  scope "(:skin)", constraints: { format: 'html' } do
    namespace :admin do
      root "claims#index"
      
      post "/letters/:id/file", to: "letters#file", as: :file_letter
      resources :claim_companies, only: [:destroy]
      resources :claims, only: [:index, :show, :edit, :update, :create] do
        resources :letters, shallow: true
        resources :messages, only: [:index, :new, :create]
        resources :documents, only: [:new, :create]
        resources :notes, only: [:index]
        resources :claim_companies, only: [:new, :create]
      end
      resources :profiles, only: [:edit, :update] do
        resource :address, only: [:new, :create]
      end
      resources :addresses, only: [:edit, :update, :destroy]
      resources :documents, only: [:show, :edit, :update, :destroy]

      resources :companies, :awards, :claim_stages
      resources :supergroups, path: "organisations", format: /html|json/
      resources :groups, path: "campaigns"

      get "/preview", to: "previews#show"
    end

    root "claims#new"

    # TODO will devise tolerate singular user?
    # No need for multiple user visibility except in the admin space
    devise_for :users, controllers: { invitations: 'users/invitations' }
    resources  :users

    resource   :profile
    # TODO nest singular address - split forms?

    # TODO singular resource for basic namespace claim?
    resources  :claims do
      resources :documents, shallow: true
      resources :claim_companies, shallow: true
    end

    resources  :companies, only: [:show] do
      # TODO singular resource for company_address?
      resources :company_addresses, shallow: true
      resources :claim_companies, shallow: true
    end
    
    resource   :feedback, only: [:new, :create], controller: 'feedback'

    resource   :feedback, only: [:new, :create], controller: 'feedback'

    # JSON lookup routes
    resources  :companies, only: [:index], constraints: { format: 'json' }
    resources  :addresses, only: [:edit, :update], constraints: { format: 'json' }

    # Membership API
    get "/membership", to: "memberships#show", as: :memberships
    # Help and custom pages
    get "/pages/:page", to: "pages#show", as: :pages

  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  include Markdownable
  include PgSearch
  
  has_one :company_address, -> { active }
  has_one :address, through: :company_address
  has_many :claim_companies, -> { active }, inverse_of: :company
  has_many :claims, through: :claim_companies
  # has_many :child_companies, class_name: "Company", foreign_key: "parent_company_id"
  # belongs_to :parent_company, class_name: "Company"
  
  accepts_nested_attributes_for :claim_companies
  
  pg_search_scope :search, against: %i(name), 
    using: { 
      tsearch: { 
        prefix: true,
        dictionary: "english"
      } 
    }
  
  validates_presence_of :name, :contact
  validate :presence_of_phone_or_email
  validate :abn_well_formed
  
  def done?
    valid? && address.present? && address.valid? && (phone || email)
  end
  
  def owners
    claims.collect(&:user)
  end
  
  def presentable_against?(claim)
    # Note: claim_companies fail validation unless they're a workplace/employer.
    claim_companies.where(claim: claim).any?
  end
  
  private
  def presence_of_phone_or_email
    unless phone.present? || email.present?
      errors.add(:company, "must contain a phone or email contact")
    end
  end
  
  def abn_well_formed
    if abn.present? && !abn_valid?(abn)
      errors.add(:abn, "must be valid.")
    end
  end
  
  def abn_valid?(abn)
    # Strip non-digits, & get an array of digits.
    abn_digits = abn.to_s.gsub(/\D/, '').chars.map(&:to_i)
    
    # Fail it if it's not 11 digits long.
    return false unless abn_digits.size == 11
    
    # Run it through the weighting, get the remainder from 89, make sure it's 0.
    abn_digits.map.with_index(&method(:abn_weighting)).sum % 89 == 0
  end
  
  def abn_weighting(n, idx)
    idx.zero? ? (n - 1) * 10 : n * ((idx + 1) * 2 - 3)
  end
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::BaseController
  before_action :set_company, only: [:edit, :update, :destroy]
  
  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(company_params)
    
    respond_to do |format|
      if @company.save
        format.html { redirect_to [:admin, @company], notice: "Company '#{@company.name}' created!" }
      else
        format.html { render :new }
      end
    end
  end
  
  def index
    @companies = Company.all
  end
  
  def show
    @company = Company.includes(:claims).find(params[:id])
  end
  
  def edit
  end
  
  def update
    @company.update_attributes(company_params)
    redirect_to [:admin, @company], notice: "Company '#{@company.name}' updated!"
  end
  
  def destroy
    @company.destroy
    redirect_to admin_companies_path
  end

  private
  def set_company
    @company = Company.find(params[:id])
  end
  
  def company_params
    params.require(:company).permit(:name, :contact, :email, :phone, :abn)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  
  # GET /companies
  def index
    @companies = params[:term] ? Company.search(params[:term]) : Company.all
    
    respond_to do |format|
      format.json { render json: @companies.to_json(include: [:address]) }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def home_title(company, claim)
    # automatically scoped to active ClaimCompanies
    claim_companies = company.claim_companies.where(claim: claim)

    result = [
      if claim_companies.any?(&:is_workplace) then t('companies.company.workplace') else nil end,
      if claim_companies.any?(&:is_employer) then t('companies.company.employer') else nil end
    ].compact.join(" & ")

    result.blank? ? result : "#{result}"
  end
end

app/views/admin/companies/_company.html.haml
%h4
  = home_title(company, claim)
  %small
    = surround "(", ")" do
      = link_to("edit", edit_admin_company_path(company))
      = "/"
      = link_to("remove", admin_claim_company_path(claim_company), data: { confirm: "Are you sure?" }, method: :delete)
:markdown
  #{markdown_model(company)}

- if company.address
  %h4
    Address
    %small= link_to("(edit)", edit_admin_address_path(company.address))

  :markdown
    #{ markdown_model(company.address) }
- else
  %h4= t('companies.company.address.heading')
  %p
    = t('companies.company.address.missing')
    = link_to t('companies.company.address.complete'), new_company_company_address_path(company), class: "btn btn-sm btn-default"

app/views/admin/companies/_form.html.haml
= form_for([:admin, @company], html: { class: "form", multipart: true }) do |f|
  = render partial: "layouts/errors", locals: { resource: @company }

  %fieldset
    %legend= "Edit company"

    .form-group
      = f.label :name, "Name", class: "control-label"
      %br/
      = f.text_field :name, class: "form-control"
      
    .form-group
      = f.label :contact, "Contact", class: "control-label"
      %br/
      = f.text_field :contact, class: "form-control"

    .form-group
      = f.label :abn, class: "control-label"
      %br/
      = f.text_field :abn, class: "form-control"

    .form-group
      = f.label :phone, "Phone", class: "control-label"
      %br/
      = f.telephone_field :phone, class: "form-control"

    .form-group
      = f.label :email, "Email", class: "control-label"
      %br/
      = f.email_field :email, class: "form-control"

  .actions.text-right= f.submit t('companies.form.commit'), class: "btn btn-default"

app/views/admin/companies/index.html.haml
.flex.flex-row-reverse.flex-center.flex-justify
  .flex-order-1
    .visible-xs
      .btn-group
        %button.btn.btn-default.btn-sm.dropdown-toggle{ type: "button", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } }
          %span.glyphicon.glyphicon-tasks
        %ul.dropdown-menu.dropdown-menu-right
          %li= link_to "Merge companies", "#", disabled: true
          %li= link_to "Create new company", new_admin_company_path

  .btn-group.hidden-xs
    = link_to "Merge companies", "#", class: "btn btn-default btn-sm", id: "merge_selected", disabled: true
    = link_to "Create new company", new_admin_company_path, class: "btn btn-default btn-sm"
    
%h2 Companies
  
-# #random_box

%table.table.table-sm
  %thead
    %tr
      %th
      %th Name
      %th{ class: "hidden-xs" } ABN
      %th Contact
      -# %th{ class: "hidden-xs" } Email
      -# %th{ class: "hidden-xs" } Phone
      %th Actions

  %tbody
    -# TODO make a partial here. It's already worth it but the pattern may see
            yet more use!
    
    - @companies.each do |co|
      %tr
        %td= check_box_tag "co_#{co.id}", "selected", false, class: "check-company", disabled: true
        %td= link_to co.name, admin_company_path(co)
        %td{ class: "hidden-xs" }= mdash_or_value(co.abn)
        %td= mdash_or_value(co.contact)
        -# %td{ class: "hidden-xs" }= mdash_or_value(co.email)
        -# %td{ class: "hidden-xs" }= mdash_or_value(co.phone)
        %td= link_to "", edit_admin_company_path(co), class: "btn btn-default btn-sm glyphicon glyphicon-pencil", title: "Edit"
        
%hr
.actions.align-right
  = link_to "Create new company", new_admin_company_path, class: "btn btn-default"

  -# :javascript
    var checked_companies;
    
    $(".check-company").on("click", function(e){
      // if (e.target.checked) {
        checked_companies = $(".check-company:checked").size();
        $("#random_box").text(checked_companies + " selected");
        
        if (checked_companies > 1) {
          $("#merge_selected").attr("disabled", false)
        } else {
          $("#merge_selected").attr("disabled", true)
        }
      //}
    })

app/views/admin/companies/new.html.haml
= render 'form'

app/views/admin/companies/show.html.haml
%h3
  = @company.name
  %small= link_to "(Edit)", edit_admin_company_path(@company)
:markdown
  #{markdown_model(@company)}

- if @company.address
  = render partial: "addresses/address", locals: { address: @company.address, title: t('companies.company.address.heading'), edit: t('companies.company.address.edit') }
  
%h3 Claims against this company
= render partial: "admin/claims/review_table", locals: { claims: @company.claims }