config/routes.rb
Rails.application.routes.draw do
  resource :incoming_message, only: [:create]

  # REMINDER shallow nests index, new, create actions
  # This scope will cause complaints for `bundle exec` commands if you've not yet
  # loaded the schema for the relevant environment.
  scope "(:skin)", constraints: { format: 'html' } do
    namespace :admin do
      root "claims#index"
      
      post "/letters/:id/file", to: "letters#file", as: :file_letter
      resources :claim_companies, only: [:destroy]
      resources :claims, only: [:index, :show, :edit, :update, :create] do
        resources :letters, shallow: true
        resources :messages, only: [:index, :new, :create]
        resources :documents, only: [:new, :create]
        resources :notes, only: [:index]
        resources :claim_companies, only: [:new, :create]
      end
      resources :profiles, only: [:edit, :update] do
        resource :address, only: [:new, :create]
      end
      resources :addresses, only: [:edit, :update, :destroy]
      resources :documents, only: [:show, :edit, :update, :destroy]

      resources :companies, :awards, :claim_stages
      resources :supergroups, path: "organisations", format: /html|json/
      resources :groups, path: "campaigns"

      get "/preview", to: "previews#show"
    end

    root "claims#new"

    # TODO will devise tolerate singular user?
    # No need for multiple user visibility except in the admin space
    devise_for :users, controllers: { invitations: 'users/invitations' }
    resources  :users

    resource   :profile
    # TODO nest singular address - split forms?

    # TODO singular resource for basic namespace claim?
    resources  :claims do
      resources :documents, shallow: true
      resources :claim_companies, shallow: true
    end

    resources  :companies, only: [:show] do
      # TODO singular resource for company_address?
      resources :company_addresses, shallow: true
      resources :claim_companies, shallow: true
    end
    
    resource   :feedback, only: [:new, :create], controller: 'feedback'

    resource   :feedback, only: [:new, :create], controller: 'feedback'

    # JSON lookup routes
    resources  :companies, only: [:index], constraints: { format: 'json' }
    resources  :addresses, only: [:edit, :update], constraints: { format: 'json' }

    # Membership API
    get "/membership", to: "memberships#show", as: :memberships
    # Help and custom pages
    get "/pages/:page", to: "pages#show", as: :pages

  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :evidence, DocumentUploader

  belongs_to :claim

  scope :hours, -> { where(time_evidence: true) }
  scope :wages, -> { where(wage_evidence: true) }

  validate :presence_of_evidence_or_statement
  validate :coverage_start_before_coverage_end

  def owners
    claim ? claim.owners : []
  end

  # document coverage - fill in gaps with fileless documents?
  # calculating gaps - get an array of days of employment and an array of days of documents
  # subtract the unique document days from the employment days, any zones left are gaps
  def days
    Set.new(coverage_start_date..coverage_end_date)
  end

  def coverage_midpoint
    days_to_midpoint = (coverage_end_date - coverage_start_date).to_i / 2

    coverage_start_date + days_to_midpoint
  end

  # Document#fy
  # Returns the financial year in which the document has more days, or the
  # earlier year if equal.
  # Alternative behaviour: pro rated hours when split over two fy's.
  def fy
    coverage_start_date.fy == coverage_end_date.fy ? coverage_start_date.fy : dominant_fy
  end

  def span_multiple_fys?
    coverage_start_date.fy != coverage_end_date.fy
  end

  def dominant_fy
    days_by_year = (coverage_start_date..coverage_end_date).to_a.group_by(&:fy)

    # this should return the earlier year in the event of a tie
    days_by_year.values.max_by(&:size).first.fy
  end

  def locked?
    claim && claim.locked?
  end

  private
  def presence_of_evidence_or_statement
    unless evidence.present? || statement.present?
      errors.add(:document, "must contain a statement or an uploaded file")
    end
  end

  def coverage_start_before_coverage_end
    if coverage_start_date > coverage_end_date
      errors.add(:coverage_start_date, "must be before coverage end date")
    end
  end
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < Admin::BaseController
  before_action :set_document, except: [:new, :create]
  before_action :set_claim, only: [:new, :create]
  # GET /documents/1
  def show
  end
  
  # GET /admin/claims/1/documents/new
  def new
    @document = Document.new
  end
  
  # POST /admin/claims/1/documents
  def create
    @document = @claim.documents.build(document_params)
    @document.evidence = document_params[:evidence]

    respond_to do |format|
      if @claim.save
        format.html do 
          if params[:repeat]
            redirect_to new_admin_claim_document_path(coverage_start_date: @document.coverage_end_date + 1.day, coverage_end_date: @document.coverage_end_date + 7.days)
          else redirect_to [:admin, @claim], notice: 'Document was successfully uploaded.' end
        end
        format.json { render :show, status: :created, location: [:admin, @document] }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /documents/1/edit
  def edit
  end
  
  # PATCH/PUT /documents/1
  def update
    respond_to do |format|
      if @document.update_attributes(document_params)
        format.html { redirect_to [:admin, @document.claim], notice: 'Document was updated.' }
        format.json { render :show, status: :ok, location: [:admin, @document] }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, @document.claim], notice: 'Document was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_claim
    @claim = Claim.find(params[:claim_id])
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:evidence, :statement, :wage_evidence, :wages, :time_evidence, :hours, :coverage_start_date, :coverage_end_date)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document, only: [:show, :destroy, :edit, :update]
  before_action :authorise_owner!, only: [:show, :destroy, :edit, :update]
  before_action :set_claim, only: [:new, :create]
  before_action :confirm_unlocked!, only: [:edit, :update, :destroy]

  # GET /documents
  # def index
  #   # TODO scope to claim
  #   @documents = Document.all
  # end

  # GET /documents/1
  def show
  end

  # GET /claims/1/documents/new
  def new
    if params[:affidavit]
      @document = Document.new(@claim.affidavit_generator)
    else
      @document = params[:document] ? Document.new(document_params) : Document.new
    end
  end

  # POST /claims/1/documents/new
  # POST /claims/1/documents/new.json
  def create
    @document = @claim.documents.build(document_params)
    @document.evidence = document_params[:evidence]

    respond_to do |format|
      if @claim.save
        format.html { redirect_to @claim, notice: 'Document was successfully uploaded.' }
        format.json { render :show, status: :created, location: @claim.user }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /documents/1/edit
  def edit
  end
  
  # PATCH/PUT /documents/1
  def update
    respond_to do |format|
      if @document.update_attributes(document_params)
        @document.claim.save
        
        format.html { redirect_to @document, notice: 'Document was updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    respond_to do |format|
      if @document.destroy
        @document.claim.save
        
        format.html { redirect_to @document.claim, notice: 'Document was successfully removed.' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def authorise_owner!
    forbidden! unless current_user && current_user.owns?(@document)
  end
  
  def set_document
    @document = Document.find(params[:id])
  end

  def set_claim
    @claim = Claim.find(params[:claim_id])
  end

  def document_params
    params.require(:document).permit(:evidence, :statement, :wage_evidence, :wages, :time_evidence, :hours, :coverage_start_date, :coverage_end_date)
  end
  
  def confirm_unlocked!
    claim = @document.claim
    
    forbidden! if claim.try(:locked?) && !current_user.try(:admin?)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def date_from_params(field)
    params[field] && Date.parse(params[field]) || Date.today
  end
  
  def date_to_time_tag(date)
    "<time datetime=#{date}>#{date.to_s(:long)}</time>"
  end

  def basename(doc)
    if doc.evidence.present?
      Pathname(doc.evidence.path).basename
    else
      "Statement"
    end
  end
end

app/views/documents/_documents.html.haml
%h3= t('.title')
- if documents.empty?
  %p= t('.empty')
- else
  %ul
    - documents.sort_by(&:coverage_midpoint).each do |doc|
      %li
        - if doc.evidence.present? && doc.evidence.is_image?
          = link_to image_tag(doc.evidence.thumb.url), doc
        = succeed ":" do
          = link_to basename(doc), doc
        = doc.coverage_start_date.to_formatted_s(:rfc822) + " – " + doc.coverage_end_date.to_formatted_s(:rfc822)
        - if current_user.owns?(doc) && !doc.locked?
          %small
            (
            = link_to(t('documents.show.edit'), edit_document_path(doc))
            |
            = link_to(t('documents.show.delete'), document_path(doc), data: { confirm: "Are you sure?" }, method: :delete)
            )

app/views/documents/_form.html.haml
= form_for([@claim, @document], html: { multipart: true }) do |f|
  = render partial: "layouts/errors", locals: { resource: @document }

  %fieldset
    %legend= t('.title')

    .form-group
      = f.label :evidence, t('.evidence'), class: "control-label"
      = f.file_field :evidence, style: "color: #BBB", class: "btn btn-default", disabled: params[:affidavit]
    
    - if params[:affidavit]
      .form-group
        = f.label :statement, t('.statement'), class: "control-label"
        %br/
        = f.text_area :statement, rows: 3, class: "form-control"

    .form-group
      .checkbox
        = f.label :wage_evidence do
          = f.check_box :wage_evidence, data: { target: "#wages" }
          = t('.wage_evidence')

      .checkbox
        = f.label :time_evidence do
          = f.check_box :time_evidence, data: { target: "#hours" }
          = t('.time_evidence')
        
    .form-group.collapse#wages
      = f.label :wages, t('.wages'), class: "control-label"
      .input-group
        .input-group-addon
          %i.glyphicon.glyphicon-usd
        = f.number_field :wages, value: number_with_precision(f.object.wages, precision: 2), class: "form-control", min: "0", step: "0.01"
      
    .form-group.collapse#hours
      = f.label :hours, t('.hours'), class: "control-label"
      .input-group
        .input-group-addon
          %i.glyphicon.glyphicon-time
        = f.number_field :hours, value: number_with_precision(f.object.hours, precision: 2), class: "form-control", min: "0", step: "0.01"

    .form-group.form-inline
      = f.label :coverage_start_date, t('.coverage_start_date'), class: "control-label"
      %br/
      = f.date_select :coverage_start_date, { selected: @document.coverage_start_date || date_from_params(:coverage_start_date), order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year - 7 }, { class: "form-control" }

    .form-group.form-inline
      = f.label :coverage_end_date, t('.coverage_end_date'), class: "control-label"
      %br/
      = f.date_select :coverage_end_date, { selected: @document.coverage_end_date || date_from_params(:coverage_end_date), order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year - 7 }, { class: "form-control" }

  .actions.text-right= f.submit t('.commit'), class: "btn btn-sm btn-default"
  
:javascript
  function boxChecked(box){
    if (box.is(":checked")){
      $(box.data().target).slideDown();
    } else {
      $(box.data().target).slideUp();
    }
  }

  $("input[type=checkbox]").on("click", function(e){
    var box = $(e.target);
    boxChecked(box);
  })
  
  $(document).ready(function(){
    $("input[type=checkbox]").each(function(index){
      var box = $(this);
      boxChecked(box);
    })
  })

app/views/documents/edit.html.haml
= form_for([@claim, @document], html: { multipart: true }) do |f|
  = render partial: "layouts/errors", locals: { resource: @document }

  %fieldset
    %legend= t('.title')

    - if @document.evidence.present?
      %p= t('documents.show.evidence')
      %p= link_to image_tag(@document.evidence.standard.url), @document.evidence.url
  
    - if @document.statement.present?
      .form-group
        = f.label :statement, t('.statement'), class: "control-label"
        %br/
        = f.text_area :statement, rows: 3, class: "form-control"

    .form-group
      .checkbox
        = f.label :wage_evidence do
          = f.check_box :wage_evidence, data: { target: "#wages" }
          = t('.wage_evidence')

      .checkbox
        = f.label :time_evidence do
          = f.check_box :time_evidence, data: { target: "#hours" }
          = t('.time_evidence')
        
    .form-group.collapse#wages
      = f.label :wages, t('.wages'), class: "control-label"
      .input-group
        .input-group-addon
          %i.glyphicon.glyphicon-usd
        = f.number_field :wages, value: number_with_precision(f.object.wages, precision: 2), class: "form-control", min: "0", step: "0.01"
      
    .form-group.collapse#hours
      = f.label :hours, t('.hours'), class: "control-label"
      .input-group
        .input-group-addon
          %i.glyphicon.glyphicon-time
        = f.number_field :hours, value: number_with_precision(f.object.hours, precision: 2), class: "form-control", min: "0", step: "0.01"

    .form-group.form-inline
      = f.label :coverage_start_date, t('.coverage_start_date'), class: "control-label"
      %br/
      = f.date_select :coverage_start_date, { selected: @document.coverage_start_date || date_from_params(:coverage_start_date), order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year - 7 }, { class: "form-control" }

    .form-group.form-inline
      = f.label :coverage_end_date, t('.coverage_end_date'), class: "control-label"
      %br/
      = f.date_select :coverage_end_date, { selected: @document.coverage_end_date || date_from_params(:coverage_end_date), order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year - 7 }, { class: "form-control" }

  .actions.text-right= f.submit t('.commit'), class: "btn btn-sm btn-default"
  
:javascript
  function boxChecked(box){
    if (box.is(":checked")){
      $(box.data().target).slideDown();
    } else {
      $(box.data().target).slideUp();
    }
  }

  $("input[type=checkbox]").on("click", function(e){
    var box = $(e.target);
    boxChecked(box);
  })
  
  $(document).ready(function(){
    $("input[type=checkbox]").each(function(index){
      var box = $(this);
      boxChecked(box);
    })
  })

app/views/documents/index.html.haml
%h1 Documents#index
%p Find me in app/views/documents/index.html.haml

app/views/documents/new.html.haml
= form_for([@claim, @document], html: { multipart: true }) do |f|
  = render partial: "layouts/errors", locals: { resource: @document }

  %fieldset
    %legend= t('.title')

    .form-group
      = f.label :evidence, t('.evidence'), class: "control-label"
      = f.file_field :evidence, style: "color: #BBB", class: "btn btn-default", disabled: params[:affidavit]
    
    - if params[:affidavit]
      .form-group
        = f.label :statement, t('.statement'), class: "control-label"
        %br/
        = f.text_area :statement, rows: 24, class: "form-control"

    .form-group
      .checkbox
        = f.label :wage_evidence do
          = f.check_box :wage_evidence, data: { target: "#wages" }
          = t('.wage_evidence')

      .checkbox
        = f.label :time_evidence do
          = f.check_box :time_evidence, data: { target: "#hours" }
          = t('.time_evidence')
        
    .form-group.collapse#wages
      = f.label :wages, t('.wages'), class: "control-label"
      .input-group
        .input-group-addon
          %i.glyphicon.glyphicon-usd
        = f.number_field :wages, value: number_with_precision(f.object.wages, precision: 2), class: "form-control", min: "0", step: "0.01"
      
    .form-group.collapse#hours
      = f.label :hours, t('.hours'), class: "control-label"
      .input-group
        .input-group-addon
          %i.glyphicon.glyphicon-time
        = f.number_field :hours, value: number_with_precision(f.object.hours, precision: 2), class: "form-control", min: "0", step: "0.01"

    .form-group.form-inline
      = f.label :coverage_start_date, t('.coverage_start_date'), class: "control-label"
      %br/
      = f.date_select :coverage_start_date, { selected: @document.coverage_start_date || date_from_params(:coverage_start_date), order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year - 7 }, { class: "form-control" }

    .form-group.form-inline
      = f.label :coverage_end_date, t('.coverage_end_date'), class: "control-label"
      %br/
      = f.date_select :coverage_end_date, { selected: @document.coverage_end_date || date_from_params(:coverage_end_date), order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year - 7 }, { class: "form-control" }

  .actions.text-right= f.submit t('.commit'), class: "btn btn-sm btn-default"
  
:javascript
  function boxChecked(box){
    if (box.is(":checked")){
      $(box.data().target).slideDown();
    } else {
      $(box.data().target).slideUp();
    }
  }

  $("input[type=checkbox]").on("click", function(e){
    var box = $(e.target);
    boxChecked(box);
  })
  
  $(document).ready(function(){
    $("input[type=checkbox]").each(function(index){
      var box = $(this);
      boxChecked(box);
    })
  })

app/views/documents/show.html.haml
%h3= basename(@document)
%p= t('.duration', beginning: date_to_time_tag(@document.coverage_start_date), end: date_to_time_tag(@document.coverage_end_date)).html_safe

%p 
  - if @document.wage_evidence
    = t('.wages', wages: number_to_currency(@document.wages))
  %br/
  - if @document.time_evidence
    = t('.hours', hours: number_with_delimiter(@document.hours))

- if @document.evidence.present?
  %p= t('.evidence')
  - if @document.evidence.is_image?
    %p= link_to image_tag(@document.evidence.standard.url), @document.evidence.url, target: "_blank"
  - else
    %p= link_to basename(@document), @document.evidence.url, target: "_blank"
  
- if @document.statement.present?
  %p= t('.statement')
  %blockquote= html_escape(@document.statement).gsub("\r\n", "<br/>").html_safe

%p
  - unless @document.locked?
    = link_to t('views.documents.show.delete'), document_path(@document), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-default"
    = link_to t('views.documents.show.edit'), edit_document_path(@document), class: "btn btn-default"
  = link_to t('views.documents.show.back'), @document.claim, class: "btn btn-default"
  